//ADD
const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
const ADD_CATEGORY_REQUEST_FAILURE = "ADD_CATEGORY_REQUEST_FAILURE";
const ADD_CATEGORY_REQUEST_SUCCESS = "ADD_CATEGORY_REQUEST_SUCCESS";

//GET ALL
const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_REQUEST_FAILURE = "GET_CATEGORIES_REQUEST_FAILURE";
const GET_CATEGORIES_REQUEST_SUCCESS = "GET_CATEGORIES_REQUEST_SUCCESS";
//REMOVE
const REMOVE_CATEGORY_REQUEST = "REMOVE_CATEGORY_REQUEST";
const REMOVE_CATEGORY_REQUEST_FAILURE = "REMOVE_CATEGORY_REQUEST_FAILURE";
const REMOVE_CATEGORY_REQUEST_SUCCESS = "REMOVE_CATEGORY_REQUEST_SUCCESS";
//UPDATE
const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
const UPDATE_CATEGORY_REQUEST_FAILURE = "UPDATE_CATEGORY_REQUEST_FAILURE";
const UPDATE_CATEGORY_REQUEST_SUCCESS = "UPDATE_CATEGORY_REQUEST_SUCCESS";

export {
  ADD_CATEGORY_REQUEST,
  ADD_CATEGORY_REQUEST_FAILURE,
  ADD_CATEGORY_REQUEST_SUCCESS,
  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_REQUEST_FAILURE,
  GET_CATEGORIES_REQUEST_SUCCESS,
  REMOVE_CATEGORY_REQUEST,
  REMOVE_CATEGORY_REQUEST_FAILURE,
  REMOVE_CATEGORY_REQUEST_SUCCESS,
  UPDATE_CATEGORY_REQUEST,
  UPDATE_CATEGORY_REQUEST_FAILURE,
  UPDATE_CATEGORY_REQUEST_SUCCESS,
};
