//ADD
const ADD_TODO_REQUEST = "ADD_TODO_REQUEST";
const ADD_TODO_REQUEST_FAILURE = "ADD_TODO_REQUEST_FAILURE";
const ADD_TODO_REQUEST_SUCCESS = "ADD_TODO_REQUEST_SUCCESS";
//GET ONE
const GET_TODO_REQUEST = "GET_TODO_REQUEST";
const GET_TODO_REQUEST_FAILURE = "GET_TODO_REQUEST_FAILURE";
const GET_TODO_REQUEST_SUCCESS = "GET_TODO_REQUEST_SUCCESS";
//GET ALL
const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
const GET_TODOS_REQUEST_FAILURE = "GET_TODOS_REQUEST_FAILURE";
const GET_TODOS_REQUEST_SUCCESS = "GET_TODOS_REQUEST_SUCCESS";
//REMOVE
const REMOVE_TODO_REQUEST = "REMOVE_TODO_REQUEST";
const REMOVE_TODO_REQUEST_FAILURE = "REMOVE_TODO_REQUEST_FAILURE";
const REMOVE_TODO_REQUEST_SUCCESS = "REMOVE_TODO_REQUEST_SUCCESS";
//UPDATE
const UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
const UPDATE_TODO_REQUEST_FAILURE = "UPDATE_TODO_REQUEST_FAILURE";
const UPDATE_TODO_REQUEST_SUCCESS = "UPDATE_TODO_REQUEST_SUCCESS";

export {
  ADD_TODO_REQUEST,
  ADD_TODO_REQUEST_FAILURE,
  ADD_TODO_REQUEST_SUCCESS,
  GET_TODO_REQUEST,
  GET_TODO_REQUEST_FAILURE,
  GET_TODO_REQUEST_SUCCESS,
  GET_TODOS_REQUEST,
  GET_TODOS_REQUEST_FAILURE,
  GET_TODOS_REQUEST_SUCCESS,
  REMOVE_TODO_REQUEST,
  REMOVE_TODO_REQUEST_FAILURE,
  REMOVE_TODO_REQUEST_SUCCESS,
  UPDATE_TODO_REQUEST,
  UPDATE_TODO_REQUEST_FAILURE,
  UPDATE_TODO_REQUEST_SUCCESS,
};
