//GET ONE
const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_REQUEST_FAILURE = "GET_USER_REQUEST_FAILURE";
const GET_USER_REQUEST_SUCCESS = "GET_USER_REQUEST_SUCCESS";

//REMOVE
const REMOVE_USER_REQUEST = "REMOVE_USER_REQUEST";
const REMOVE_USER_REQUEST_FAILURE = "REMOVE_USER_REQUEST_FAILURE";
const REMOVE_USER_REQUEST_SUCCESS = "REMOVE_USER_REQUEST_SUCCESS";
//UPDATE
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_REQUEST_FAILURE = "UPDATE_USER_REQUEST_FAILURE";
const UPDATE_USER_REQUEST_SUCCESS = "UPDATE_USER_REQUEST_SUCCESS";

export {
  GET_USER_REQUEST,
  GET_USER_REQUEST_FAILURE,
  GET_USER_REQUEST_SUCCESS,
  REMOVE_USER_REQUEST,
  REMOVE_USER_REQUEST_FAILURE,
  REMOVE_USER_REQUEST_SUCCESS,
  UPDATE_USER_REQUEST,
  UPDATE_USER_REQUEST_FAILURE,
  UPDATE_USER_REQUEST_SUCCESS,
};
