CREATE DATABASE perntodo;

CREATE TABLE todo(
    todo_id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE ,
    description VARCHAR(255),
    category VARCHAR(255) 
);

CREATE TABLE category(
category_id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE ,
name VARCHAR(255),
user_id BIGSERIAL NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE userTodo (
    usertodo_id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE ,
    user_id BIGSERIAL NOT NULL REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    todo_id BIGSERIAL NOT NULL REFERENCES todo(todo_id) ON UPDATE CASCADE ON DELETE CASCADE,
    rol_id INTEGER NOT NULL REFERENCES role(role_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE role(
role_id SERIAL PRIMARY KEY NOT NULL UNIQUE,
name VARCHAR(255)
);


CREATE TABLE permission(
 permission_id SERIAL PRIMARY KEY NOT NULL UNIQUE,
 name VARCHAR(255),
 role_id INTEGER NOT NULL REFERENCES role(role_id) ON UPDATE CASCADE ON DELETE CASCADE
);



CREATE TABLE users (
user_id BIGSERIAL PRIMARY KEY NOT NULL UNIQUE,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE  NOT NULL,
password VARCHAR(255) NOT NULL
);


INSERT INTO role (name) VALUES ('Admin');
INSERT INTO role (name) VALUES ('Viewr');
SELECT * FROM role;